name: Deploy

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME  }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD  }}

on:
  push:
    branches: [ educates-workshop ]
  repository_dispatch:
    types: cat-meow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          .github/workflows/deploy.sh

      # # Uncomment the following to enable updating kustomize tag
      # - name: Update Tag
      #   run: |
      #     curl -X POST \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -H "Authorization: token ${{ secrets.GIT_PASSWORD  }}" \
      #     --data '{"event_type": "tag", "client_payload": { "version": "1.2.3"}}' \
      #     https://api.github.com/repos/${{ secrets.GIT_USERNAME  }}/cat-service/dispatches
